// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhdzdyxbdqqcyvxyfptz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoZHpkeXhiZHFxY3l2eHlmcHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTgxMTAsImV4cCI6MjA2ODQzNDExMH0.T2TDNVOJ9rxH4zfscGiFQZbxBsVsZsL5GvnPKrtvO9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});